# Generated by Django 3.1.3 on 2020-11-29 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netkineskop', '0002_auto_20201125_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channeltag',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='netkineskop.channel'),
        ),
        migrations.AlterField(
            model_name='channeltag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='netkineskop.tag'),
        ),
    ]
