# Generated by Django 3.1.3 on 2020-12-03 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('netkineskop', '0003_auto_20201129_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='name',
        ),
        migrations.AlterField(
            model_name='channel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='channeltag',
            unique_together={('tag', 'channel')},
        ),
    ]
