# Generated by Django 3.1.3 on 2020-12-04 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netkineskop', '0004_auto_20201203_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(blank=True, default='<name placeholder>', max_length=128),
        ),
        migrations.AlterField(
            model_name='channeltag',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netkineskop.channel'),
        ),
        migrations.AlterField(
            model_name='channeltag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netkineskop.tag'),
        ),
    ]
